### ISSUE TITLE
Error: Record on line 4: wrong number of fields

### ISSUE THREAD

**Issue by Daboposki** [xzebra/unizar-calendar#23]
Al darle al botón de enviar consulta en la web con esta entrada:
![imagen](https://user-images.githubusercontent.com/24795695/109066323-3268fc80-76ed-11eb-9aa2-1000b3e018e8.png)
![imagen](https://user-images.githubusercontent.com/24795695/109066333-3563ed00-76ed-11eb-81e2-35a03311528c.png)

aparece el siguiente error:
![imagen](https://user-images.githubusercontent.com/24795695/109066415-5593ac00-76ed-11eb-859a-b55bc9f07ecb.png)

**Comment by xzebra** [comment]
he conseguido replicarlo: sucede cuando una fila recién creada tiene la descripción vacía

supongo que por algún null al crear la fila o algo así

**Comment by xzebra** [comment]
ocurre tambien con la tabla de abajo
